apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:    
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nginx
        image: nginx
  selector:
    matchLabels:
      app: webapp
  replicas: 4