apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod 
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx:1.20.2
  selector:
    matchLabels:
      app: frontend-app
  replicas: 6