kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: vote  
  labels:
    app: redis  
spec:
  ports:
    - name: "redis-service"
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
  selector:
    app: redis