kind: Service
apiVersion: v1
metadata:
  name: db
  namespace: vote  
  labels:
    app: db  
spec:
  ports:
    - name: "db-service"
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
  selector:
    app: db