apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql-app
spec:
  containers:
    - name: nginx
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATASE
          value: gekk